### PR TITLE
Throw more informative exception messages

### LINKED ISSUE #14: Better exception for when rendering a bundle that doesn't exist.
In a view, if you 

```
@await SmidgeHelper.JsHereAsync("DoesntExist")
```

Where there is no such bundle, you gte an error like this:

image

Should throw a more helpful / indicative error.

### LINKED ISSUE #25: Better exception for when bundling a file that doesn't exist
If you try to create a bundle, but one of the file's cannot be found:

image

The exception doesn't tell you the problematic file path however, this would be better if it told you which path can not be found.

### PR DESCRIPTION
**Pull request by dazinator**
This fixes #25
and fixes #14
Has unit tests

BTW - Any ideas what I need to change to stop these diff's going crazy?

### CODE REVIEW

**Comment by Shazwazza** [comment]
It's all white space changes, you can append ?w=1 to the end of the url in github to tell it to ignore white space

**Comment by dazinator** [comment]
Ah ok.. that's useful to know!
Although under the hood, there is still the issue that these files are actually being modified unnecessarily - even if it is just whitespace changes,
I think this might be down to us having different global config for git "Line endings" setting.
This can be fixed by creating a .gitattributes file within the the repo, to specify how line endings should be dealt with. More info here: 

http://stackoverflow.com/questions/170961/whats-the-best-crlf-carriage-return-line-feed-handling-strategy-with-git

Might be worth looking into!

**Comment by dazinator** [comment]
Here is a screenshot of what this error looks like now:

image

**Comment by dazinator** [comment]
Hope you don't mind i'm gonna chuck some more stuff in this PR

**Comment by Shazwazza** [comment]
Sounds good :)

**Comment by dazinator** [comment]
And this is now what the exception looks like when you try to render a bundle that doesn't exist: 
image

**Comment by dazinator** [comment]
Ok think that's it for this PR, it was just those couple of issues to throw more informative exceptions.

**Comment by Shazwazza** [comment]
Looks wonderful! I'll merge + test, really hoping to find time to get a release out this week. I'll also look into the gitattributes file, seems like a very easy win

**Pull request merged**
