### PR TITLE
Check for invalid characters.

### PR DESCRIPTION
**Pull request by PhyxionNL**
See #171
@Shazwazza Best viewed without whitespace changes. I reformatted/cleaned up some bits to make VS a little bit happier.

This includes the ability to configure the compression level (for bundles only, defaults to the existing CompressionLevel.Optimal).

### CODE REVIEW

**Comment by PhyxionNL** [comment]
NuGet API key must be renewed I think.

**Comment by PhyxionNL** [comment]
@Shazwazza Can we get this merged? 👀

**Comment by Shazwazza** [comment]
Hi thanks for the PR and sorry for the delay.

Is it possible to split this PR into 2 - one for the actual fix with
minimal changes and another for code cleanup?

In the future, if you can keep fixes and changes separate from mass code
cleanup that would be great, else it's quite difficult to see functional or
breaking changes.

**Comment by PhyxionNL** [comment]
Viewing the changes without whitespace would've address that almost completely, but I have removed it. What's still there is the file character check and an additional compression level option (defaults to current Optimal) for bundles. Should be trivial to review now 😊

**Comment by PhyxionNL** [comment]
Let me create a new PR, Git doesn't want to squash.

**Pull request closed without merging**
