### PR TITLE
Use HeaderNames

### PR DESCRIPTION
**Pull request by PhyxionNL**
No need to redefine all these header names.

### CODE REVIEW

**Comment by PhyxionNL** [comment]
@Shazwazza this one should be squashed.

**Comment by Shazwazza** [comment]
Changes look good but there might be a missing using clause or something, the build errors out with

> Error: /home/runner/work/Smidge/Smidge/src/Smidge/Controllers/CheckNotModifiedAttribute.cs(78,69): error CS0117: 'HttpConstants' does not contain a definition for 'NotModified304' [/home/runner/work/Smidge/Smidge/src/Smidge/Smidge.csproj]

**Comment by Shazwazza** [comment]
I'll merge and fixup the build errors. Cheers!

**Comment by PhyxionNL** [comment]
The history was messed up locally. I tried to fix it with a force push but somehow that file was left (didn't notice). The file should be this one (which is the one from the other PR):
https://github.com/PhyxionNL/Smidge/commit/9bc32321587bed91f2fc86f976bc4c31c8ec4654

**Comment by Shazwazza** [comment]
Awesome, yep saw the merge just worked so all good :)

**Pull request merged**
