### PR TITLE
Fixes #10 and #12

### LINKED ISSUE #10: Support adding config directly to appSettings.json
I am just in the process of setting Smidge up (thanks for making this!)
I noticed this bit:

> Add a config file to your app root (not wwwroot) called smidge.json with this content:

Would it be possible for configuration to be added to the `appSettings.json` file instead? If Smidge uses IConfiguration this should just work?

### PR DESCRIPTION
**Pull request by dazinator**
AddSmidge() method now allows you to pass in your own IConfiguration, which allows you to use some other Configuration Source aside from the default which is the smidge.json file.

Note: Sorry, I think there is an issue with line endings..

### CODE REVIEW

**Comment by dazinator** [comment]
I have created a temporary "unlisted" NuGet package on NuGet.org from this PR here: https://www.nuget.org/packages/Smidge-DazinatorTempFork/0.1.0-pr10

**Comment by dazinator** [comment]
My last commit also addresses #12 by making the `FileSystemHelper` a bit more intelligent in how it goes about resolving file locations - it now leverages the `IFileProvider.

**Comment by dazinator** [comment]
Temportary NuGet package published form this PR [here](I have added a temporary "unlisted" NuGet package to NuGet.org, built from this PR, here: https://www.nuget.org/packages/SmidgePr-DazinatorTempFork/0.1.1-pr10)

**Comment by Shazwazza** [comment]
I'm back from holidays now, will review all of this this week! :)

**Comment by Shazwazza** [comment]
This all looks really great! I'll pull this in and test.

**Comment by Shazwazza** [comment]
I just wonder, if we are allowing the usage of 'any' configuration files, the smidge configuration keys should probably be prefixed right ? Like: "smidge.dataFolder" and "smidge.version" ?

**Comment by dazinator** [comment]
Thanks for looking at this!

The key names are up to you, but I don't think a prefix is really necessary as people can use config sections. 

For example, I do this:

```
            var bundlerConfig = config.GetSection("smidge");
            services.AddSmidge(bundlerConfig)
```

and my appSettings.json:

```
{

 "smidge": {     
        "dataFolder": "App_Data/Bundler",
        "version": "1"    
    },
}  

```

I find this quite nice, because people can nest the config for smidge wherever they like given how they want to structure their settings. i.e:

```
{
"modules": {     
  "bundling": {     
      "smidge": {     
        "dataFolder": "App_Data/Bundler",
        "version": "1" 
        },
    },      
}  

```

And then:

```
            var bundlerConfig = config.GetSection("modules:bundling:smidge");
            services.AddSmidge(bundlerConfig)
```

**Comment by Shazwazza** [comment]
Ah, wonderful! I'll update the code in the web proj with this too

**Pull request merged**
