### PR TITLE
Fixes #31

### LINKED ISSUE #31: JsMin - Singleton not thread safe
Running the website from master, hit a problem on site startup that happens sporadically:

image

Following through the code this happens when two threads / tasks access JsMin at the same time. This happens for me randomly on startup of the website and not sure why - it doesn't always seem to happen. 

`JsMin` isn't thread safe, so both threads enter JSMin and create an instance of a writer and store it in the same private field:

image

One thread then disposes of that instance, and the second thread hits the exception trying to write to the now disposed instance.

JsMin is registered as a singleton instance:

```
 services.AddSingleton<IPreProcessor, JsMin>();
```

The simplest fix for this would be to register it as scoped I guess.

I'll make that change unless you spot an issue with that.

This may explain some of the other odd issues I was seeing, if the same reader and writer was being used by different threads / minification tasks then it may have garbled the input / output leading to weird exceptions.

### PR DESCRIPTION
**Pull request by dazinator**
Register JsMin as Scoped rather than a Singleton to address conccurent thread issues.

I also added the project.lock.json files and some other files to the gitignore file so they don't keep on showing up for future check ins.

### CODE REVIEW

**Comment by dazinator** [comment]
Hmm for some reason I am still seeing the same instance of `JsMin` being used. I think this needs further investigation.

**Comment by dazinator** [comment]
I think it may be to do with the fact that `PreProcessPipelineFactory` is a singleton, and it keeps hold of and reuses the `IPreProcessor` instances.

**Comment by dazinator** [comment]
I'm thinking this may all be easier to refactor JsMin to make it thread safe perhaps.

**Comment by Shazwazza** [comment]
Yeah, it's all my fault :P Sorry about this. There's a few ways I can fix this. I think some of the pre-processors will require a non singleton context so we'll need to allow for that. A quick fix is to make the jsmin pre-processor a separate singleton class like JsMinPreprocessor which then creates new instances of JsMin whenever it does it's processing. I didn't get time today to update this but now realize that I need to change how the lifetimes are managed due to what you just mentioned about PreProcessPipelineFactory.

**Comment by dazinator** [comment]
No worries. Yeah creating a new instance looks like an easy change. I'll try that!

**Comment by dazinator** [comment]
Ok - I think that last commit was hopefully what you meant as the interim solution!

**Pull request merged**
