### PR TITLE
Target NET 7.0

### LINKED ISSUE #179: Consider targeting for .NET 7
Consider adding .NET 7 in Directory.Build.props for all Smidge.* packages.

### PR DESCRIPTION
**Pull request by erdihu**
This PR tries to resolve #179 
I don't have much experience about nuget packages but if any other changes are needed I can try to do those as well.

### CODE REVIEW

**Comment by Shazwazza** [comment]
Looks pretty good! Prob don't need to install both .NET 7 and 6 in the GH actions (I could be wrong though). I'll test soon. Thanks!

**Comment by PhyxionNL** [comment]
> Looks pretty good! Prob don't need to install both .NET 7 and 6 in the GH actions (I could be wrong though). I'll test soon. Thanks!

It would be necessary, but instead of adding this task three times, it could just be one like this:

```
  with:
    dotnet-version: | 
      5.0.x
      6.0.x
      7.0.x
```

But we really should drop 3..x and 5.x in Smidge given that they're long out of support.

**Comment by Shazwazza** [comment]
@PhyxionNL Any chance you might have time to clone this fork and make that update to this PR?

**Comment by PhyxionNL** [comment]
With or without old .NETs?

**Pull request closed without merging**
